server:
  address: "0.0.0.0"
  port: 10071
spring:
  application:
    name: reservation-service
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
